name: Release iOS

# only when version-io file changes, the action runs
# tag triggering doesn't support caching
on:
  push:
    paths:
      - "version-ios"
      - ".github/workflows/release-ios.yml"
      - "exportOptions.plist"

env:
  PROJECT_NAME: PocketBroomball
  WORKING_DIRECTORY: game
  EXPORT_PRESET_CFG: ${{ secrets.GODOT_EXPORTS_PRESET_CFG }}

jobs:
  deploy:
    runs-on: macos-12
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set version and short version
        run: echo "VERSION=$(cat version-ios)" >> $GITHUB_ENV

      - name: Create and config export_presets.cfg
        run: |
          echo $EXPORT_PRESET_CFG > $WORKING_DIRECTORY/export_presets.cfg
          sed -i -e "s|VERSION_CODE|$VERSION|g" $WORKING_DIRECTORY/export_presets.cfg
          sed -i -e "s|VERSION_NAME|$VERSION|g" $WORKING_DIRECTORY/export_presets.cfg
          sed -i -e "s|IOS_SHORT_VERSION|$VERSION|g" $WORKING_DIRECTORY/export_presets.cfg
          sed -i -e "s|IOS_VERSION|$VERSION|g" $WORKING_DIRECTORY/export_presets.cfg
          cat $WORKING_DIRECTORY/export_presets.cfg

      - name: Export and release to Testflight
        uses: dulvui/godot-ios-release@v0.1
        with:
          working-directory: $WORKING_DIRECTORY
          project-name: $PROJECT_NAME
          certificate-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          provision-profile-base64: ${{ secrets.PROVISION_PROFILE_BASE64 }}
          p12-password: ${{ secrets.P12_PASSWORD }}
          apple-id-username: ${{ secrets.APPLE_ID_USERNAME }}
          apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
          cache-version: 2